# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Example Site"
weight = 1

[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Sean的博客"
weight = 1
